name: Upload Python Package

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pdm-project/setup-pdm@973541a5febeafcfdadf8a51211435be6ecfd90f # v4.5
      - name: Build package
        run: pdm build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@6733eb7d741f0b11ec6a39b58540dab7590f9b7d # v1.14.0
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
